// lib/tokenConfig.ts

/* -------------------------------- Types -------------------------------- */

export type Cluster = "mainnet" | "devnet";

export type TokenCategory =
  | "Top MC"
  | "Stocks"
  | "DeFi"
  | "Infrastructure"
  | "Meme"
  | "LST"
  | "DePin"
  | "Gaming"
  | "NFT"
  | "Privacy"
  | "PreMarket"
  | "Utility"
  | "Commodity"
  | "Fund"
  | "ETF";

export type TokenKind = "crypto" | "stock";

export type TokenMeta = {
  name: string;
  symbol: string;
  id?: string; // slug
  logo: string; // /public path
  kind: TokenKind;

  /** Multi-category (core filtering) */
  categories: TokenCategory[];

  /** Optional micro-filters (secondary UI chips) */
  tags?: string[];

  decimals?: number;
  mints: Partial<Record<Cluster, string>>;
};

/* ------------------------------- Env/Utils ----------------------------- */

export function getCluster(): Cluster {
  const raw = (process.env.NEXT_PUBLIC_SOLANA_CLUSTER || "").toLowerCase();
  if (raw.includes("dev")) return "devnet";
  return "mainnet";
}

export const WSOL_MINT = "So11111111111111111111111111111111111111112";

/** UI-config flat fee shown to user when swapping/buying */
export const CRYPTO_FLAT_FEE_USDC_UI: number = (() => {
  const raw = process.env.NEXT_PUBLIC_CRYPTO_FEE_UI ?? "0.20";
  const n = Number(raw);
  return Number.isFinite(n) && n >= 0 ? n : 0.2;
})();

export const CRYPTO_TOKENS: TokenMeta[] = [
  // ---------------- Top MC (Crypto + tokenized assets)
  {
    name: "Solana",
    symbol: "SOL",
    id: "solana",
    logo: "/logos/sol.png",
    kind: "crypto",
    categories: ["Top MC", "Infrastructure"],
    tags: ["L1"],
    decimals: 9,
    mints: { mainnet: WSOL_MINT, devnet: WSOL_MINT },
  },
  {
    name: "Bitcoin",
    symbol: "BTC",
    id: "bitcoin",
    logo: "/logos/btc.png",
    kind: "crypto",
    categories: ["Top MC"],
    tags: ["Store of Value"],
    decimals: 8,
    mints: { mainnet: "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh" },
  },
  {
    name: "Ethereum",
    symbol: "ETH",
    id: "ethereum",
    logo: "/logos/eth.png",
    kind: "crypto",
    categories: ["Top MC", "Infrastructure"],
    tags: ["L1"],
    decimals: 8,
    mints: { mainnet: "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs" },
  },
  {
    name: "Near",
    symbol: "NEAR",
    id: "near",
    logo: "/logos/near.png",
    kind: "crypto",
    categories: ["Infrastructure"],
    tags: ["L1"],
    decimals: 8,
    mints: { mainnet: "3ZLekZYq2qkZiSpnSvabjit34tUkjSwD1JFuW9as9wBG" },
  },
  {
    name: "Monad",
    symbol: "MON",
    id: "monad",
    logo: "/logos/mon.png",
    kind: "crypto",
    categories: ["Infrastructure"],
    tags: ["L1"],
    decimals: 8,
    mints: { mainnet: "CrAr4RRJMBVwRsZtT62pEhfA9H5utymC2mVx8e7FreP2" },
  },

  // ---------------- DeFi / Infra / DePin / Memes / LSTs
  {
    name: "Raydium",
    symbol: "RAY",
    id: "raydium",
    logo: "/logos/ray.jpg",
    kind: "crypto",
    categories: ["DeFi"],
    tags: ["DEX"],
    decimals: 8,
    mints: { mainnet: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R" },
  },
  {
    name: "Meteora",
    symbol: "MET",
    id: "meteora",
    logo: "/logos/met.png",
    kind: "crypto",
    categories: ["DeFi"],
    tags: ["DEX"],
    decimals: 8,
    mints: { mainnet: "METvsvVRapdj9cFLzq4Tr43xK4tAjQfwX76z3n6mWQL" },
  },
  {
    name: "Drift Protocol",
    symbol: "DRIFT",
    id: "drift-protocol",
    logo: "/logos/drift.png",
    kind: "crypto",
    categories: ["DeFi"],
    tags: ["DEX"],
    decimals: 8,
    mints: { mainnet: "DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7" },
  },
  {
    name: "deBridge",
    symbol: "DBR",
    id: "debridge",
    logo: "/logos/dbr.png",
    kind: "crypto",
    categories: ["DeFi"],
    tags: ["DEX"],
    decimals: 8,
    mints: { mainnet: "DBRiDgJAMsM95moTzJs7M9LnkGErpbv9v6CUR1DXnUu5" },
  },
  {
    name: "Jupiter",
    symbol: "JUP",
    id: "jupiter-exchange-solana",
    logo: "/logos/jup.webp",
    kind: "crypto",
    categories: ["DeFi", "Infrastructure"],
    tags: ["Aggregator", "DEX"],
    decimals: 8,
    mints: { mainnet: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN" },
  },
  {
    name: "Kamino",
    symbol: "KMNO",
    id: "kamino",
    logo: "/logos/kmno.jpg",
    kind: "crypto",
    categories: ["DeFi"],
    tags: ["Lending", "Vaults"],
    decimals: 8,
    mints: { mainnet: "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS" },
  },
  {
    name: "Bonk",
    symbol: "BONK",
    id: "bonk",
    logo: "/logos/bonk.jpg",
    kind: "crypto",
    categories: ["Meme"],
    tags: ["Community"],
    decimals: 8,
    mints: { mainnet: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263" },
  },
  {
    name: "Pump.fun",
    symbol: "PUMP",
    id: "pump-fun",
    logo: "/logos/pump.jpg",
    kind: "crypto",
    categories: ["Meme"],
    tags: ["Launchpad"],
    decimals: 8,
    mints: { mainnet: "pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn" },
  },
  {
    name: "DogWifHat",
    symbol: "WIF",
    id: "dogwifcoin",
    logo: "/logos/wif.jpg",
    kind: "crypto",
    categories: ["Meme"],
    tags: ["Community"],
    decimals: 8,
    mints: { mainnet: "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm" },
  },
  {
    name: "FARTCOIN",
    symbol: "FART",
    id: "fartcoin",
    logo: "/logos/fart.png",
    kind: "crypto",
    categories: ["Meme"],
    tags: ["Community"],
    decimals: 8,
    mints: { mainnet: "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump" },
  },

  // LSTs
  {
    name: "Drift Staked SOL",
    symbol: "DSOL",
    id: "drift-staked-sol",
    logo: "/logos/dsol.png",
    kind: "crypto",
    categories: ["LST", "DeFi"],
    tags: ["Staking"],
    decimals: 9,
    mints: { mainnet: "Dso1bDeDjCQxTrWHqUUi63oBvV7Mdm6WaobLbQ7gnPQ" },
  },
  {
    name: "Marinade Staked SOL",
    symbol: "MSOL",
    id: "msol",
    logo: "/logos/msol.webp",
    kind: "crypto",
    categories: ["LST", "DeFi"],
    tags: ["Staking"],
    decimals: 9,
    mints: { mainnet: "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So" },
  },
  {
    name: "Jito Staked SOL",
    symbol: "JITOSOL",
    id: "jito-staked-sol",
    logo: "/logos/Jitosol.png",
    kind: "crypto",
    categories: ["LST", "DeFi"],
    tags: ["Staking", "MEV"],
    decimals: 9,
    mints: { mainnet: "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn" },
  },
  {
    name: "Jupiter Staked SOL",
    symbol: "JUPSOL",
    id: "jupiter-staked-sol",
    logo: "/logos/jupsol.png",
    kind: "crypto",
    categories: ["LST", "DeFi"],
    tags: ["Staking"],
    decimals: 9,
    mints: { mainnet: "jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v" },
  },
  {
    name: "Helius Staked SOL",
    symbol: "HSOL",
    id: "helius-staked-sol",
    logo: "/logos/hsol.png",
    kind: "crypto",
    categories: ["LST", "DeFi", "Infrastructure"],
    tags: ["Staking", "RPC"],
    decimals: 9,
    mints: { mainnet: "he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A" },
  },

  // DePin
  {
    name: "Render",
    symbol: "RENDER",
    id: "render-token",
    logo: "/logos/rndr.png",
    kind: "crypto",
    categories: ["DePin"],
    tags: ["GPU"],
    decimals: 9,
    mints: { mainnet: "rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof" },
  },
  {
    name: "DoubleZero",
    symbol: "2Z",
    id: "doublezero",
    logo: "/logos/2z.png",
    kind: "crypto",
    categories: ["DePin"],
    tags: ["Network"],
    decimals: 9,
    mints: { mainnet: "J6pQQ3FAcJQeWPPGppWRb4nM8jU3wLyYbRrLh7feMfvd" },
  },
  {
    name: "Helium",
    symbol: "HNT",
    id: "helium",
    logo: "/logos/hnt.png",
    kind: "crypto",
    categories: ["DePin"],
    tags: ["Wireless"],
    decimals: 9,
    mints: { mainnet: "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux" },
  },
  {
    name: "Hivemapper",
    symbol: "HONEY",
    id: "hivemapper",
    logo: "/logos/honey.png",
    kind: "crypto",
    categories: ["DePin"],
    tags: ["Mapping"],
    decimals: 9,
    mints: { mainnet: "4vMsoUT2BWatFweudnQM1xedRLfJgJ7hswhcpz4xgBTy" },
  },
  {
    name: "Grass",
    symbol: "GRASS",
    id: "grass",
    logo: "/logos/grass.png",
    kind: "crypto",
    categories: ["DePin"],
    tags: ["Bandwidth"],
    decimals: 9,
    mints: { mainnet: "Grass7B4RdKfBCjTKgSqnXkqjwiGvQyFbuSCUJr3XXjs" },
  },
  {
    name: "ZCash",
    symbol: "ZEC",
    id: "omnibridge-bridged-zcash-solana",
    logo: "/logos/zec.png",
    kind: "crypto",
    categories: ["Privacy"],
    tags: ["Privacy"],
    decimals: 9,
    mints: { mainnet: "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS" },
  },
  {
    name: "GhostWareOS",
    symbol: "GHOST",
    id: "ghostwareos",
    logo: "/logos/ghost.png",
    kind: "crypto",
    categories: ["Privacy"],
    tags: ["Privacy"],
    decimals: 9,
    mints: { mainnet: "BBKPiLM9KjdJW7oQSKt99RVWcZdhF6sEHRKnwqeBGHST" },
  },

  // NFT / Meme adjacent
  {
    name: "Pudgy Penguins",
    symbol: "PENGU",
    id: "pudgy-penguins",
    logo: "/logos/pengu.png",
    kind: "crypto",
    categories: ["Meme", "NFT"],
    tags: ["Brand"],
    decimals: 9,
    mints: { mainnet: "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv" },
  },
  {
    name: "Metaplex",
    symbol: "MPLX",
    id: "metaplex",
    logo: "/logos/mplx.png",
    kind: "crypto",
    categories: ["NFT", "Infrastructure"],
    tags: ["Brand"],
    decimals: 9,
    mints: { mainnet: "METAewgxyPbgwsseH8T16a39CQ5VyVxZi9zXiDPY18m" },
  },

  // DeFi
  {
    name: "Jupiter Liquidity Perps",
    symbol: "JLP",
    id: "jupiter-perpetuals-liquidity-provider-token",
    logo: "/logos/jlp.jpg",
    kind: "crypto",
    categories: ["DeFi"],
    tags: ["Perps", "LP"],
    decimals: 8,
    mints: { mainnet: "27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4" },
  },
  {
    name: "Orca",
    symbol: "ORCA",
    id: "orca",
    logo: "/logos/orca.png",
    kind: "crypto",
    categories: ["DeFi"],
    tags: ["DEX"],
    decimals: 6,
    mints: { mainnet: "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE" },
  },
  {
    name: "Pyth Network",
    symbol: "PYTH",
    id: "pyth-network",
    logo: "/logos/pyth.png",
    kind: "crypto",
    categories: ["Infrastructure"],
    tags: ["Oracles"],
    decimals: 6,
    mints: { mainnet: "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3" },
  },
  {
    name: "Switchboard",
    symbol: "SWTCH",
    id: "switchboard",
    logo: "/logos/swtch.png",
    kind: "crypto",
    categories: ["DeFi", "Infrastructure"],
    tags: ["Oracles"],
    decimals: 9,
    mints: { mainnet: "SW1TCHLmRGTfW5xZknqQdpdarB8PD95sJYWpNp9TbFx" },
  },
  {
    name: "HYPE",
    symbol: "HYPE",
    id: "wormhole-bridged-hype",
    logo: "/logos/hype.png",
    kind: "crypto",
    categories: ["DeFi", "Infrastructure"],
    tags: ["DEX"],
    decimals: 9,
    mints: { mainnet: "98sMhvDwXj1RQi5c5Mndm3vPe9cBqPrbLaufMXFNMh5g" },
  },
  {
    name: "Jito",
    symbol: "JTO",
    id: "jito-governance-token",
    logo: "/logos/jto.png",
    kind: "crypto",
    categories: ["DeFi", "Infrastructure"],
    tags: ["DEX"],
    decimals: 9,
    mints: { mainnet: "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL" },
  },
];

export const STOCK_TOKENS: TokenMeta[] = [
  // ---------------- Stocks (tokenized)
  {
    name: "American Airlines Group",
    symbol: "AALON",
    id: "american-airlines-group-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71401/large/abton_160x160.png?1767874963",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "9wYZetvT8J2ptfsRca5gzLBGvcUug38mp9yT3xaondo",
    },
  },
  {
    name: "Apple",
    symbol: "AAPLON",
    id: "apple-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68616/large/aaplon_160x160.png?1756130122",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "123mYEnRLM2LLYsJW3K6oyYh8uP1fngj732iG638ondo",
    },
  },
  {
    name: "AbbVie",
    symbol: "ABBVON",
    id: "abbvie-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71398/large/abbvon_160x160.png?1767874645",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "MFerpBVGKZh2jXN7cbJdXRXQTp6j6pbSnSZrfWrondo",
    },
  },
  {
    name: "Airbnb",
    symbol: "ABNBON",
    id: "airbnb-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68565/large/abnbon_160x160.png?1756106088",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "128qNYovdGv2YqayErcJgU7gDwbNVX1VuoxbtWz8ondo",
    },
  },
  {
    name: "Abbott",
    symbol: "ABTON",
    id: "abbott-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68552/large/abton_160x160.png?1756105660",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "129gRoHKhVg7CvPMrqVsEB4uYZo6zV4yDZX6NBg9ondo",
    },
  },
  {
    name: "Archer Aviation",
    symbol: "ACHRON",
    id: "archer-aviation-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71405/large/achron_160x160.png?1767875526",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "KcCVQxG9LhFYP5o9DWFKTFgFShPPQkDEemVbiFyondo",
    },
  },
  {
    name: "Accenture",
    symbol: "ACNON",
    id: "accenture-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68610/large/acnon_160x160.png?1756130072",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "12LxMMJYVSf4LoeqjFE47BQQNRciaH9E3nbDfjH4ondo",
    },
  },
  {
    name: "Adobe",
    symbol: "ADBEON",
    id: "adobe-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68622/large/adbeon_160x160.png?1756130258",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "12Rh6JhfW4X5fKP16bbUdb4pcVCKDHFB48x8GG33ondo",
    },
  },
  {
    name: "Analog Devices",
    symbol: "ADION",
    id: "analog-devices-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71403/large/adion_160x160.png?1767875295",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "LmTMwmZLNZszn3qpjmnbhfP12U4qWDivaEBwSBSondo",
    },
  },
  {
    name: "iShares Core US Aggregate Bond ETF",
    symbol: "AGGON",
    id: "ishares-core-us-aggregate-bond-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68561/large/aggon_160x160.png?1756105956",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "13qTjKx53y6LKGGStiKeieGbnVx3fx1bbwopKFb3ondo",
    },
  },
  {
    name: "Applied Materials",
    symbol: "AMATON",
    id: "applied-materials-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71404/large/amaton_160x160.png?1767875400",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "7eRX747PSbVtGVx3qD5UFdkNM2BfTy86ikUiCMhondo",
    },
  },
  {
    name: "AMC Entertainment",
    symbol: "AMCON",
    id: "amc-entertainment-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71400/large/amcon_160x160.png?1767874892",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "C9xNaNujcF1a5fidWAAFReFYqhLRVbyk4yPyGqzondo",
    },
  },
  {
    name: "AMD",
    symbol: "AMDON",
    id: "amd-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68589/large/amdon_160x160.png?1756129814",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "14diAn5z8kjrKwSC8WLqvBqqe5YmihJhjxRxd8Z6ondo",
    },
  },
  {
    name: "Amgen",
    symbol: "AMGNON",
    id: "amgen-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71402/large/amgnon_160x160.png?1767875106",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "SS6AEWhzRrxhL2cXzKKjhFt3rCzmHHGKmFyugDTondo",
    },
  },
  {
    name: "Amazon",
    symbol: "AMZNON",
    id: "amazon-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68604/large/amznon_160x160.png?1756129958",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "14Tqdo8V1FhzKsE3W2pFsZCzYPQxxupXRcqw9jv6ondo",
    },
  },
  {
    name: "Arista Networks",
    symbol: "ANETON",
    id: "arista-networks-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71406/large/aneton_160x160.png?1767875613",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "Cq6QtvHpXbJWtFaiMhUDtHy8YVZ95gcD1oZ1cohondo",
    },
  },
  {
    name: "Apollo Global Management",
    symbol: "APOON",
    id: "apollo-global-management-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68586/large/apoon_160x160.png?1756129798",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "14VXAhoa1R74vi1ZuiQyGLJrnDMfoFBPJSCpGVz3ondo",
    },
  },
  {
    name: "AppLovin",
    symbol: "APPON",
    id: "applovin-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68615/large/appon_160x160.png?1756130115",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "14Z8rQQe2Aza33YgEUmj3g3QGNz8DXLiFPuCnsD1ondo",
    },
  },
  {
    name: "Arm Holdings plc",
    symbol: "ARMON",
    id: "arm-holdings-plc-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68572/large/armon_160x160.png?1756106342",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "15SsCZqCsM9fZGhTmP4rdJTPT9WGZKazDSsgeQ8ondo",
    },
  },
  {
    name: "ASML Holding NV",
    symbol: "ASMLON",
    id: "asml-holding-nv-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68642/large/asmlon_160x160.png?1756156077",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "1eLZPRsn8bAKmoxsqDMH9Q2m2k7GMNp6RLSQGm8ondo",
    },
  },
  {
    name: "Broadcom",
    symbol: "AVGOON",
    id: "broadcom-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68601/large/avgoon_160x160.png?1756129937",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "1FWZtdWN7y38BSXGzbs8D6Shk88oL9atDNgbVz9ondo",
    },
  },
  {
    name: "American Express",
    symbol: "AXPON",
    id: "american-express-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68607/large/axpon_160x160.png?1756130045",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "1WxT6NdK7uqpfXuKpALxL2n3f7Rq61XXeHA8UM4ondo",
    },
  },
  {
    name: "Alibaba",
    symbol: "BABAON",
    id: "alibaba-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68600/large/babaon_160x160.png?1756129931",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "1zvb9ELBFShBCWKEk5jRTJAaPAwtVt7quEXx1X4ondo",
    },
  },
  {
    name: "Bank of America",
    symbol: "BACON",
    id: "bank-of-america-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71408/large/bacon_160x160.png?1767876029",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "Wk8gC6iTNp8dqd4ghkJ3h1giiUnyhykwHh7tYWjondo",
    },
  },
  {
    name: "Boeing",
    symbol: "BAON",
    id: "boeing-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68613/large/baon_160x160.png?1756130096",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "1YVZ4LGpq8CAhpdpm3mgy7GgPb83gJczCpxLUQ3ondo",
    },
  },
  {
    name: "BigBear.ai Holdings",
    symbol: "BBAION",
    id: "bigbear-ai-holdings-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71409/large/bbaion_160x160.png?1767876297",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "YXE7mph6XhsgnyezkMEcTuohSuWhbLWfwx2Hh6mondo",
    },
  },
  {
    name: "Baidu",
    symbol: "BIDUON",
    id: "baidu-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68591/large/biduon_160x160.png?1756129824",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "54CoRF2FYMZNJg9tS36xq5BUcLZ7rju1r59jGc2ondo",
    },
  },
  {
    name: "Bilibili",
    symbol: "BILION",
    id: "bilibili-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71410/large/bilion_160x160.png?1767879051",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "14kLsQVmc64qZexYuR4XGop9y8BeMkd77pJUm1Rhondo",
    },
  },
  {
    name: "iShares Flexible Income Active ETF",
    symbol: "BINCON",
    id: "ishares-flexible-income-active-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/71433/large/bincon_160x160.png?1767883050",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "mhZ69E1vDnAsQJXAwarLYSX5tmgeMajXBJ2rXAcondo",
    },
  },
  {
    name: "Blackrock, Inc.",
    symbol: "BLKON",
    id: "blackrock-inc-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68629/large/blkon_160x160.png?1756130314",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "5H1VpMzRuoNtRbPTRCz35ETtEUtnkt8hJuQb9v7ondo",
    },
  },
  {
    name: "Bullish",
    symbol: "BLSHON",
    id: "bullish-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71413/large/blshon_160x160.png?1767879289",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "A9PFmw9Hu8zzxDUoU351pio1E1XWBWBfWnjT9qoondo",
    },
  },
  {
    name: "BitMine Immersion Technologies",
    symbol: "BMNRON",
    id: "bitmine-immersion-technologies-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71411/large/bmnron_160x160.png?1767879134",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "MYXqkDYbzr7vjXAz2BapR4AiYRXzoikGirrLoRzondo",
    },
  },
  {
    name: "B2Gold",
    symbol: "BTGON",
    id: "b2gold-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71407/large/btgon_160x160.png?1767875934",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "cBnVXDyZgaaLZM18wAmqsUKnRUFAEJWbq6VuUoaondo",
    },
  },
  {
    name: "BitGo Holdings",
    symbol: "BTGOON",
    id: "bitgo-holdings-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71702/large/btgoon_160x160.png?1769009385",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "bgJWGuQxyoyFeXwzYZKBmoujVdatGFYPNFnv1a6ondo",
    },
  },
  {
    name: "Kanzhun",
    symbol: "BZON",
    id: "kanzhun-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71436/large/bzon_160x160.png?1767883251",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "doPqjCxi6UkANkvMz5fSuYGEo5PGppVpTZMeB5vondo",
    },
  },
  {
    name: "Caterpillar",
    symbol: "CATON",
    id: "caterpillar-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71572/large/caton_160x160.webp?1768404047",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "AErxJJxGbc9cZzZoZepN62BNfg5RXns8tmEc3Zpondo",
    },
  },
  {
    name: "Constellation Energy",
    symbol: "CEGON",
    id: "constellation-energy-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71575/large/cegon_160x160.webp?1768404796",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "7NWHifsBnn9DimUeNnsHdEXkTZhXmJTiXxcCngBondo",
    },
  },
  {
    name: "Cipher Mining",
    symbol: "CIFRON",
    id: "cipher-mining-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71573/large/cifron_160x160.webp?1768404416",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "WNZBSkNBNP3Ct1pcFn6Fu4sZQFhnu48EsM9voCEondo",
    },
  },
  {
    name: "iShares AAA CLO Active ETF",
    symbol: "CLOAON",
    id: "ishares-aaa-clo-active-etf-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71578/large/cloaon_160x160.webp?1768405146",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "t71FyTYHVkPAb5g48adDHmkVxXYbUuP2eq6jDZLondo",
    },
  },
  {
    name: "VanEck CLO ETF",
    symbol: "CLOION",
    id: "vaneck-clo-etf-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71585/large/cloion_160x160.webp?1768406304",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "ucQ3VfWAx9pkCN4Kg84zE56FtB4FJN2kQH4ArYYondo",
    },
  },
  {
    name: "Chipotle",
    symbol: "CMGON",
    id: "chipotle-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68567/large/cmgon_160x160.png?1756106157",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "5owVsVFSHACQuippFYdLp3qWRobp2EGcwxMmsr6ondo",
    },
  },
  {
    name: "Capital One",
    symbol: "COFON",
    id: "capital-one-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71571/large/cofon_160x160.webp?1768403857",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "R2uDbMtmHq5xSS5SserrovdRKdpiqnVBCd2AHLhondo",
    },
  },
  {
    name: "Coinbase",
    symbol: "COINON",
    id: "coinbase-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68612/large/coinon_160x160.png?1756130090",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "5u6KDiNJXxX4rGMfYT4BApZQC5CuDNrG6MHkwp1ondo",
    },
  },
  {
    name: "Citigroup",
    symbol: "CON",
    id: "citigroup-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71574/large/con_160x160.webp?1768404610",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "PjtfUiw6Hwd8PZ94EcUw8mBSYxp7SjjzSLeNTDKondo",
    },
  },
  {
    name: "ConocoPhillips",
    symbol: "COPON",
    id: "conocophillips-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71416/large/copon_160x160.png?1767880759",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "X68p9qTpEMkR1TLpXUP2ZJo8PG4Qge2Y2ZLdjA2ondo",
    },
  },
  {
    name: "Global X Copper Miners ETF",
    symbol: "COPXON",
    id: "global-x-copper-miners-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/71424/large/copxon_160x160.png?1767882136",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "X7j77hTmjZJbepkXXBcsEapM8qNgdfihkFj6CZ5ondo",
    },
  },
  {
    name: "Costco",
    symbol: "COSTON",
    id: "costco-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68648/large/coston_160x160.png?1756156219",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "6btaz134wjHkR8sqhAYrtSM6tavftfxnRvnyMd8ondo",
    },
  },
  {
    name: "Coupang",
    symbol: "CPNGON",
    id: "coupang-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71417/large/cpngon_160x160.png?1767880918",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "NKyzy31w2J7odLb2CW3Ft4fpKXkW3LBt1pvpkVLondo",
    },
  },
  {
    name: "Circle Internet Group",
    symbol: "CRCLON",
    id: "circle-internet-group-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68595/large/crclon_160x160.png?1756129889",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "6xHEyem9hmkGtVq6XGCiQUGpPsHBaoYuYdFNZa5ondo",
    },
  },
  {
    name: "Salesforce",
    symbol: "CRMON",
    id: "salesforce-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68603/large/crmon_160x160.png?1756129951",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "7D7ukbcnUNYt7Et5vtsDZhAy28MKu9pkHka1Hp9ondo",
    },
  },
  {
    name: "CrowdStrike",
    symbol: "CRWDON",
    id: "crowdstrike-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71418/large/crwdon_160x160.png?1767881071",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "cdKfoNjbXgnSuxvoajhtH3uixfZhq1YXhQsS1Rwondo",
    },
  },
  {
    name: "Cisco Systems",
    symbol: "CSCOON",
    id: "cisco-systems-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68566/large/cscoon_160x160.png?1756106113",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "7DWcZE1uVc8m2mf9pV8KNov28ET7HsvHkhrhgr9ondo",
    },
  },
  {
    name: "Carvana",
    symbol: "CVNAON",
    id: "carvana-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71414/large/cvnaon_160x160.png?1767879516",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "FGmUDXqA3AbWfo5b3NUcsvwoUFCF4tr9ea6uercondo",
    },
  },
  {
    name: "Chevron",
    symbol: "CVXON",
    id: "chevron-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68597/large/cvxon_160x160.png?1756129908",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "7tgKziACteG26VjV5xKufojKxwTgCFyTwmWUmz5ondo",
    },
  },
  {
    name: "DoorDash",
    symbol: "DASHON",
    id: "doordash-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68609/large/dashon_160x160.png?1756130064",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "83P1gCFBZfGRCwJuBt9juxJKEsZwejJoG66eTZ6ondo",
    },
  },
  {
    name: "Invesco DB Commodity Index Tracking Fund",
    symbol: "DBCON",
    id: "invesco-db-commodity-index-tracking-fund-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/71429/large/dbcon_160x160.png?1767882634",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "td1aY5AvYQuwGD75qNq9aPipMexraN9mQXJwqifondo",
    },
  },
  {
    name: "Deere",
    symbol: "DEON",
    id: "deere-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71419/large/deon_160x160.png?1767881213",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "CqQyAZjB9LGFTG95eiadGTkfhd9QA12ProeKsQmondo",
    },
  },
  {
    name: "Disney",
    symbol: "DISON",
    id: "disney-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68587/large/dison_160x160.png?1756129802",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "mJf1xT3suXtkXBCfZcE9oUUuyxkvSgqYBWiX7v1ondo",
    },
  },
  {
    name: "Denison Mines",
    symbol: "DNNON",
    id: "denison-mines-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71420/large/dnnon_160x160.png?1767881289",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "12J2LD3tuLfdiVKnWZMHRMrbnXDY9rM4yqVLUa5yondo",
    },
  },
  {
    name: "iShares MSCI Emerging Markets ETF",
    symbol: "EEMON",
    id: "ishares-msci-emerging-markets-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68550/large/eemon_160x160.png?1756105571",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "916SDKz7y5ZcEZC9CtnQ5Djs1Y8Yv3UAPb6bak8ondo",
    },
  },
  {
    name: "iShares MSCI EAFE ETF",
    symbol: "EFAON",
    id: "ishares-msci-eafe-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68555/large/efaon_160x160.png?1756105748",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "AbvryMGnaba9oADMZk8Vp2Av6MtczsncGyfWaC4ondo",
    },
  },
  {
    name: "Equinix",
    symbol: "EQIXON",
    id: "equinix-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68546/large/eqixon_160x160.png?1756105357",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "aheEdmuryJU8ymy8LjYheZH5i2BW1UMsfuWQKD2ondo",
    },
  },
  {
    name: "Figma Ord Shs",
    symbol: "FIGON",
    id: "figma-ord-shs-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68656/large/figon_160x160.png?1756156375",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "aLDdFsr3VTUQaHFK6yNvQxztvxQ8nxW4AMuSGC7ondo",
    },
  },
  {
    name: "Figure Technology Solutions",
    symbol: "FIGRON",
    id: "figure-technology-solutions-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71576/large/figron_160x160.webp?1768404918",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "ZmHxc6Gt27RJKxD2ay6UL4n9yQ7mKAq4XZQUeVhondo",
    },
  },
  {
    name: "Ford Motor",
    symbol: "FON",
    id: "ford-motor-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71577/large/fon_160x160.webp?1768405022",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "5hT2o25X9tGXipwhLckaUdgnxrZ6Y8eiUwdhpLeondo",
    },
  },
  {
    name: "First Trust Global Tactical Commodity Strategy Fund",
    symbol: "FTGCON",
    id: "first-trust-global-tactical-commodity-strategy-fund-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71422/large/ftgcon_160x160.png?1767881800",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "ivBnfPTyuHDNWmMSnbavckhJK6SHZW8h77nZKsEondo",
    },
  },
  {
    name: "Futu Holdings",
    symbol: "FUTUON",
    id: "futu-holdings-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68568/large/futuon_160x160.png?1756106205",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "Ao5rKFRQ54W3DKSAtqfhBRPNHewwWRLNLao2JL9ondo",
    },
  },
  {
    name: "Gemini Space Station",
    symbol: "GEMION",
    id: "gemini-space-station-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71423/large/gemion_160x160.png?1767882038",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "NrTdGMA3ujUvWXkwXyZKnhoByb32KTjRh5Vo47yondo",
    },
  },
  {
    name: "General Electric",
    symbol: "GEON",
    id: "general-electric-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68614/large/geon_160x160.png?1756130103",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "aTBfDuLRqYHBiG82bHA7DzwjSDTFre2dRtGH3S5ondo",
    },
  },
  {
    name: "SPDR Gold Shares ",
    symbol: "GLDON",
    id: "spdr-gold-shares-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71467/large/gldon_160x160.png?1767891536",
    kind: "stock",
    categories: ["Stocks", "Commodity"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "hWfiw4mcxT8rnNFkk6fsCQSxoxgZ9yVhB6tyeVcondo",
    },
  },
  {
    name: "GameStop",
    symbol: "GMEON",
    id: "gamestop-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68575/large/gmeon_160x160.png?1756864181",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "aznKt8v32CwYMEcTcB4bGTv8DXWStCpHrcCtyy7ondo",
    },
  },
  {
    name: "Alphabet Class A",
    symbol: "GOOGLON",
    id: "alphabet-class-a-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68606/large/googlon_160x160.png?1756130033",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "bbahNA5vT9WJeYft8tALrH1LXWffjwqVoUbqYa1ondo",
    },
  },
  {
    name: "Grab Holdings",
    symbol: "GRABON",
    id: "grab-holdings-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71425/large/grabon_160x160.png?1767882216",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "m9GcsVgdjaL3KsdtSFHimnhtsUMpTHkjtwEG4Tzondo",
    },
  },
  {
    name: "Goldman Sachs",
    symbol: "GSON",
    id: "goldman-sachs-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68621/large/gson_160x160.png?1756130252",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "BchJRy2snmhJZf3rQ9LJ3ePs2BGfYgfvQNo31d2ondo",
    },
  },
  {
    name: "Home Depot",
    symbol: "HDON",
    id: "home-depot-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71427/large/hdon_160x160.png?1767882478",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "MtEXKVN3Pcggy8MPA3eJr15H6SK3RXheScqj9qtondo",
    },
  },
  {
    name: "Hims & Hers Health",
    symbol: "HIMSON",
    id: "hims-hers-health-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68553/large/himson_160x160.png?1756105686",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "bdh3njeo19d2TBLAKTGvCWdSoArfVw8uZBAJHY4ondo",
    },
  },
  {
    name: "Robinhood Markets",
    symbol: "HOODON",
    id: "robinhood-markets-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68581/large/hoodon_160x160.png?1756129765",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "BVdXGvmgi6A9oAiwWvBvP76fyTqcCNRJMM7zMN6ondo",
    },
  },
  {
    name: "iBoxx $ High Yield Corporate Bond ETF",
    symbol: "HYGON",
    id: "iboxx-high-yield-corporate-bond-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68544/large/hygon_160x160.png?1756105272",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "c5ug15fwZRfQhhVa6LHscFY33ebVDHcVCezYpj7ondo",
    },
  },
  {
    name: "iShares Gold Trust",
    symbol: "IAUON",
    id: "ishares-gold-trust-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68653/large/iauon_160x160.png?1756156321",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "M77ZvkZ8zW5udRbuJCbuwSwavRa7bGAZYMTwru8ondo",
    },
  },
  {
    name: "IBM",
    symbol: "IBMON",
    id: "ibm-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68608/large/ibmon_160x160.png?1756130056",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "C8bZkgSxXkyT1RgxByp2teJ24hgimPLoyEYoNa9ondo",
    },
  },
  {
    name: "iShares Core MSCI EAFE ETF",
    symbol: "IEFAON",
    id: "ishares-core-msci-eafe-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68558/large/iefaon_160x160.png?1756105856",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "C9J9vZ8N79GzzxFoRkPWCkGtMKU8akg4FhUk4r9ondo",
    },
  },
  {
    name: "iShares Core MSCI Emerging Markets ETF",
    symbol: "IEMGON",
    id: "ishares-core-msci-emerging-markets-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68658/large/iemgon_160x160.png?1756156411",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "cdVNL7wK8mf1UCDqM6zdrziRv4hmvqWhXeTcck2ondo",
    },
  },
  {
    name: "iShares Core S&P MidCap ETF",
    symbol: "IJHON",
    id: "ishares-core-s-p-midcap-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68611/large/ijhon_160x160.png?1756130078",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "cfPLN9WXD2BTkbZhRZMVXPmVSiRo44hJWRtnaC8ondo",
    },
  },
  {
    name: "Intel",
    symbol: "INTCON",
    id: "intel-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68557/large/intcon_160x160.png?1756105832",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "cJpUMp5R7rZ6fGeLHbHhrRuJzK9mkyKDjZqNpT3ondo",
    },
  },
  {
    name: "Intuit",
    symbol: "INTUON",
    id: "intuit-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68619/large/intuon_160x160.png?1756130237",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "CozoH5HBTyyeYSQxHcWpGzd4Sq5XBaKzBzvTtN3ondo",
    },
  },
  {
    name: "IREN",
    symbol: "IRENON",
    id: "iren-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71431/large/irenon_160x160.png?1767882809",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "13QHuepdhtJ3urNsV9i1hdL8nQoca2G7ZaLzb5FYondo",
    },
  },
  {
    name: "Intuitive Surgical",
    symbol: "ISRGON",
    id: "intuitive-surgical-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71428/large/isrgon_160x160.png?1767882550",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "1MGRpPrkhEsCm2GCWD3rsvEU77xTTLAzfKXeFgFondo",
    },
  },
  {
    name: "iShares Core S&P Total US Stock Market ETF",
    symbol: "ITOTON",
    id: "ishares-core-s-p-total-us-stock-market-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68543/large/itoton_160x160.png?1756105177",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "CPWkMURVvcnX8hGjqCTb8i5LkzV3VSvyk7SeJi8ondo",
    },
  },
  {
    name: "iShares Core S&P 500 ETF",
    symbol: "IVVON",
    id: "ishares-core-s-p-500-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68650/large/ivvon_160x160.png?1756156270",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "CqW2pd6dCPG9xKZfAsTovzDsMmAGKJSDBNcwM96ondo",
    },
  },
  {
    name: "iShares Russell 1000 Growth ETF",
    symbol: "IWFON",
    id: "ishares-russell-1000-growth-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68570/large/iwfon_160x160.png?1756106267",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "dSHPFuMMjZqt7xDYGWrexXTSkdEZAiZngqymQF2ondo",
    },
  },
  {
    name: "iShares Russell 2000 ETF",
    symbol: "IWMON",
    id: "ishares-russell-2000-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68646/large/iwmon_160x160.png?1756156170",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "dvj2kKFSyjpnyYSYppgFdAEVfgjMEoQGi9VaV23ondo",
    },
  },
  {
    name: "iShares Russell 2000 Value ETF",
    symbol: "IWNON",
    id: "ishares-russell-2000-value-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68540/large/iwnon_160x160.png?1756105013",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "DX7g7WNjDpVzNK9CG81v7wb6ZbiNzYfkdzH2Xs5ondo",
    },
  },
  {
    name: "Janus Henderson AAA CLO ETF",
    symbol: "JAAAON",
    id: "janus-henderson-aaa-clo-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/71434/large/jaaaon_160x160.png?1767883134",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "KZtqx9BJbpcGY7vdzhqPXM3ECKChxE5YhXaDiwRondo",
    },
  },
  {
    name: "JD.com",
    symbol: "JDON",
    id: "jd-com-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68573/large/jdon_160x160.png?1756106373",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "E1aUS5nyv7kaBzdQzPVJW5zfaMgoUJpKYzdnFS2ondo",
    },
  },
  {
    name: "Johnson & Johnson",
    symbol: "JNJON",
    id: "johnson-johnson-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71435/large/jnjon_160x160.png?1767883191",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "KUXt7LzHWSQXp5eyqMZRxWjAP6yM8BUh4LRHwiwondo",
    },
  },
  {
    name: "JPMorgan Chase",
    symbol: "JPMON",
    id: "jpmorgan-chase-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68602/large/jpmon_160x160.png?1756129944",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "E5Gczsavxcomqf6Cw1sGCKLabL1xYD2FzKxVoB4ondo",
    },
  },
  {
    name: "KLA ",
    symbol: "KLACON",
    id: "kla-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71437/large/klacon_160x160.png?1767889328",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "149o8ppQf9SzKCKXZ4v3dzHkwumvtQSRzSEkr29uondo",
    },
  },
  {
    name: "Coca-Cola",
    symbol: "KOON",
    id: "coca-cola-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68569/large/koon_160x160.png?1756106230",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "e6G4pfFcrdKxJuZ4YXixRFfMbpMvgXG2Mjcus71ondo",
    },
  },
  {
    name: "Linde plc",
    symbol: "LINON",
    id: "linde-plc-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68571/large/linon_160x160.png?1756106308",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "Edik9MoFp8LAXS9HNu2gRFyihwYqDqv4ZmNmVT9ondo",
    },
  },
  {
    name: "Li Auto ",
    symbol: "LION",
    id: "li-auto-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71439/large/lion_160x160.png?1767889433",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "v12TwfofSbvVqQ5N5KGG4d3J8rtEi4BjGfn2apyondo",
    },
  },
  {
    name: "Eli Lilly",
    symbol: "LLYON",
    id: "eli-lilly-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68643/large/llyon_160x160.png?1756156107",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "eGGxZwNSfuNKRqQLKaz2hc4QkA2mau7skyxPdj7ondo",
    },
  },
  {
    name: "Lockheed",
    symbol: "LMTON",
    id: "lockheed-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68618/large/lmton_160x160.png?1756130231",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "EoReHwUnGGekbXFHLj5rbCVKiwWqu32GrETMfw4ondo",
    },
  },
  {
    name: "Lowe's",
    symbol: "LOWON",
    id: "lowe-s-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71440/large/lowon_160x160.png?1767889494",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "edLdFJVVR532qhcrNTJjLAmhmyV7NsctbWVokMBondo",
    },
  },
  {
    name: "Lam Research",
    symbol: "LRCXON",
    id: "lam-research-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71438/large/lrcxon_160x160.png?1767889373",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "wFJoeEYpKg9oRhyJy6BWTT3J95gmXBLvoeikDQNondo",
    },
  },
  {
    name: "Mastercard",
    symbol: "MAON",
    id: "mastercard-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68617/large/maon_160x160.png?1756130130",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "EsVHcyRxXFJCLMiuYLWhoDygrNe1BJGpYeZ17X7ondo",
    },
  },
  {
    name: "MARA Holdings",
    symbol: "MARAON",
    id: "mara-holdings-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68548/large/maraon_160x160.png?1756105480",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "ETCJUmuhs5aY62xgEVWCZ5JR8KPdeXUaJz3LuC5ondo",
    },
  },
  {
    name: "McDonald's",
    symbol: "MCDON",
    id: "mcdonald-s-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68620/large/mcdon_160x160.png?1756130244",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "EUbJjmDt8JA222M91bVLZs211siZ2jzbFArH9N3ondo",
    },
  },
  {
    name: "MercadoLibre",
    symbol: "MELION",
    id: "mercadolibre-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68652/large/melion_160x160.png?1756156305",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "EWwdgGshGngcMpDV34pWZRSu5bkAuiKuKTTHKQ8ondo",
    },
  },
  {
    name: "Meta Platforms",
    symbol: "METAON",
    id: "meta-platforms-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68645/large/metaon_160x160.png?1756156152",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "fDxs5y12E7x7jBwCKBXGqt71uJmCWsAQ3Srkte6ondo",
    },
  },
  {
    name: "MP Materials ",
    symbol: "MPON",
    id: "mp-materials-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71444/large/mpon_160x160.png?1767889675",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "XwFm5GiKPVTvPiEbQpdc6vJbFEpsUXRMf6TcSxnondo",
    },
  },
  {
    name: "Merck",
    symbol: "MRKON",
    id: "merck-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71442/large/mrkon_160x160.png?1767889571",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "bn1fb8dwzafGePqNPrM8m8cbAKQiFqeEPuZkPySondo",
    },
  },
  {
    name: "Moderna",
    symbol: "MRNAON",
    id: "moderna-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71443/large/mrnaon_160x160.png?1767889634",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "14VP7DvCAdBCc5XGNZkPt6zhtPzJrWWS64Koxtxyondo",
    },
  },
  {
    name: "Marvell Technology",
    symbol: "MRVLON",
    id: "marvell-technology-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68560/large/mrvlon_160x160.png?1756105919",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "FovBwhoV5KQjZCdhoM6jgXYwXLX3F8vgAfvmLH7ondo",
    },
  },
  {
    name: "Microsoft",
    symbol: "MSFTON",
    id: "microsoft-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68625/large/msfton_160x160.png?1756130286",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "FRmH6iRkMr33DLG6zVLR7EM4LojBFAuq6NtFzG6ondo",
    },
  },
  {
    name: "MicroStrategy",
    symbol: "MSTRON",
    id: "microstrategy-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68530/large/mstron_160x160.png?1756100941",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "FSz4ouiqXpHuGPcpacZfTzbMjScoj5FfzHkiyu2ondo",
    },
  },
  {
    name: "MasTec ",
    symbol: "MTZON",
    id: "mastec-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71441/large/mtzon_160x160.png?1767889534",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "R3ywbVQ5t8LNmjQsn2Ngv43dSqyZscQwNag9G3Eondo",
    },
  },
  {
    name: "Micron Technology",
    symbol: "MUON",
    id: "micron-technology-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68574/large/muon_160x160.png?1756106401",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "Fz9edBpaURPPzpKVRR1A8PENYDEgHqwx5D5th28ondo",
    },
  },
  {
    name: "NextEra Energy",
    symbol: "NEEON",
    id: "nextera-energy-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71446/large/neeon_160x160.png?1767889812",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "t7eN6cGwRMFaZvsNW2SmVwkedmHtDdrxA4ycNE5ondo",
    },
  },
  {
    name: "Netflix",
    symbol: "NFLXON",
    id: "netflix-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68649/large/nflxon_160x160.png?1756156245",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "g4KnPrxPLeeKkwvDmZFMtYQPM64eHeShbD55vK6ondo",
    },
  },
  {
    name: "Sprott Nickel Miners ETF (Ondo Tokenized)",
    symbol: "NIKLON",
    id: "sprott-nickel-miners-etf-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71468/large/niklon_160x160.png?1767891579",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "V8LRV7kWjrx6Prke9oHEHNUiR122BVtyuPciTCTondo",
    },
  },
  {
    name: "NIO ",
    symbol: "NIOON",
    id: "nio-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71447/large/nioon_160x160.png?1767889848",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "yQ37dFiGAbzrb2FRAEhGNzRy5zFfoYGWYhAepFEondo",
    },
  },
  {
    name: "Nike",
    symbol: "NKEON",
    id: "nike-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68556/large/nkeon_160x160.png?1756105802",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "g646pcdG2Rt5DH9WZzL7VVnVDWCCMTTrnktwE74ondo",
    },
  },
  {
    name: "ServiceNow",
    symbol: "NOWON",
    id: "servicenow-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68644/large/nowon_160x160.png?1756156127",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "G7pTVoSECz5RQWubEnTP7AC83KHUsSyoiqYR1R2ondo",
    },
  },
  {
    name: "NetEase ",
    symbol: "NTESON",
    id: "netease-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71445/large/nteson_160x160.png?1767889779",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "YeK2TdPtGLAme3Phg4pb1GBN2YxKgX5UNVyD4asondo",
    },
  },
  {
    name: "NVIDIA",
    symbol: "NVDAON",
    id: "nvidia-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68623/large/nvdaon_160x160.png?1756130268",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "gEGtLTPNQ7jcg25zTetkbmF7teoDLcrfTnQfmn2ondo",
    },
  },
  {
    name: "Novo Nordisk",
    symbol: "NVOON",
    id: "novo-nordisk-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68554/large/nvoon_160x160.png?1756105715",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "GeV7S8vjP8qdYZpdGv2Xi6e7MUMCk8NAAp2z7g5ondo",
    },
  },
  {
    name: "Oklo ",
    symbol: "OKLOON",
    id: "oklo-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71449/large/okloon_160x160.png?1767889913",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "m6oDLvJT7rY7M1TxuLWP3pWmAPg2cCWDQR1NKiEondo",
    },
  },
  {
    name: "Ondas Holdings",
    symbol: "ONDSON",
    id: "ondas-holdings-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71451/large/ondson_160x160.png?1767889983",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "7qy1j4Mechfyr6uAST3djH4vk4kiEYC2cjEytXdondo",
    },
  },
  {
    name: "ON Semiconductor ",
    symbol: "ONON",
    id: "on-semiconductor-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71450/large/onon_160x160.png?1767889948",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "13qtwy5fZi9Przz14pzo9xqFSr8QHmLyUpUCvP1xondo",
    },
  },
  {
    name: "Opendoor Technologies ",
    symbol: "OPENON",
    id: "opendoor-technologies-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71452/large/openon_160x160.png?1767890016",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "ou1uE526v7zmUYP2qCb2LJgfXAyWAtWS9SETtr8ondo",
    },
  },
  {
    name: "Opera ",
    symbol: "OPRAON",
    id: "opera-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71453/large/opraon_160x160.png?1767890056",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "gbHFTMkuMQUy5xrgoCBdaQ2XYvNyjWAYcnRPh9Condo",
    },
  },
  {
    name: "Oracle",
    symbol: "ORCLON",
    id: "oracle-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68592/large/orclon_160x160.png?1756129828",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "GmDADFpfwjfzZq9MfCafMDTS69MgVjtzD7Fd9a4ondo",
    },
  },
  {
    name: "Oscar Health ",
    symbol: "OSCRON",
    id: "oscar-health-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71454/large/oscron_160x160.png?1767890097",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "ThwGDsXZ6iKubWuEQjmDxGwF3bUERDGbBXvcbjFondo",
    },
  },
  {
    name: "Occidental Petroleum",
    symbol: "OXYON",
    id: "occidental-petroleum-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71448/large/oxyon_160x160.png?1767889881",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "1GNFMryQ6c9ZpMhgNimmsbtgYM21qnBJgRAFoNiondo",
    },
  },
  {
    name: "abrdn Physical Palladium Shares ETF",
    symbol: "PALLON",
    id: "abrdn-physical-palladium-shares-etf-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71399/large/pallon_160x160.png?1767874802",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "P7hTXnKk2d2DyqWnefp5BSroE1qjjKpKxg9SxQqondo",
    },
  },
  {
    name: "Palo Alto Networks",
    symbol: "PANWON",
    id: "palo-alto-networks-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68599/large/panwon_160x160.png?1756129923",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "M7hVQomhw4Q2D2op3HvBrZjHu9SryjNvD5haEZ1ondo",
    },
  },
  {
    name: "Petrobras",
    symbol: "PBRON",
    id: "petrobras-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68545/large/pbron_160x160.png?1756105320",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "GRciFCqJ5y2hbiD6U5mGkohY65BZTXGuGUrCqf7ondo",
    },
  },
  {
    name: "PG&E ",
    symbol: "PCGON",
    id: "pg-e-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71456/large/pcgon_160x160.png?1767890294",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "UP5s1srLaHDc4SwJqLPa3A48x5R7ofN3hZWxWEZondo",
    },
  },
  {
    name: "Invesco Optimum Yld Dvsfd Cmd Str No K-1 ETF",
    symbol: "PDBCON",
    id: "invesco-optimum-yld-dvsfd-cmd-str-no-k-1-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/71430/large/pdbcon_160x160.png?1767882707",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "M6agiXbNgy8Xon9ngiW4ZDPbMFcNCTMkMMkshZyondo",
    },
  },
  {
    name: "PDD Holdings ",
    symbol: "PDDON",
    id: "pdd-holdings-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71455/large/pddon_160x160.png?1767890129",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "PnjETBCLC318DRejo9cMQKAmET9PvW8AEFGWMNtondo",
    },
  },
  {
    name: "PepsiCo",
    symbol: "PEPON",
    id: "pepsico-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68588/large/pepon_160x160.png?1756129807",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "gud6b3fYekjhMG5F818BALwbg2vt4JKoow59Md9ondo",
    },
  },
  {
    name: "Pfizer",
    symbol: "PFEON",
    id: "pfizer-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68549/large/pfeon_160x160.png?1756105512",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "Gwh9fPsX1qWATXy63vNaJnAFfwebWQtZaVmPko6ondo",
    },
  },
  {
    name: "Procter & Gamble",
    symbol: "PGON",
    id: "procter-gamble-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68593/large/pgon_160x160.png?1756129875",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "GZ8v4NdSG7CTRZqHMgNsTPRULeVi8CpdWd9wZY8ondo",
    },
  },
  {
    name: "Pinterest ",
    symbol: "PINSON",
    id: "pinterest-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71457/large/pinson_160x160.png?1767890343",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "sxyg1VTSzy5zYANUK7hntNtmFAWoXGJq95AcHuVondo",
    },
  },
  {
    name: "Palantir Technologies",
    symbol: "PLTRON",
    id: "palantir-technologies-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68594/large/pltron_160x160.png?1756129883",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "HfsnTS5qtdStwec9DfBrunRqnAMYMMz1kjv9Hu9ondo",
    },
  },
  {
    name: "Plug Power",
    symbol: "PLUGON",
    id: "plug-power-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71458/large/plugon_160x160.png?1767890383",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "TnfswqdE1jAJ8sfnf5J7kSVLEH1cfpAYZ8MWmKfondo",
    },
  },
  {
    name: "ProShares Short QQQ ",
    symbol: "PSQON",
    id: "proshares-short-qqq-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71459/large/psqon_160x160.png?1767890433",
    kind: "stock",
    categories: ["Stocks", "Fund"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "qKtU9A7ij34XmtxaSzYfxCpkgAZzzFsqnUb2kW2ondo",
    },
  },
  {
    name: "PayPal",
    symbol: "PYPLON",
    id: "paypal-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68551/large/pyplon_160x160.png?1756105622",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "hM7B3UQTTR81mS27SxDDPzBbjejmo8fnpFjzgv9ondo",
    },
  },
  {
    name: "D-Wave Quantum",
    symbol: "QBTSON",
    id: "d-wave-quantum-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68541/large/qbtson_160x160.png?1756105094",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "hqJXutLF6f7DxStrWCrnZDfXzbNTZmvi3KheVi6ondo",
    },
  },
  {
    name: "Qualcomm",
    symbol: "QCOMON",
    id: "qualcomm-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68563/large/qcomon_160x160.png?1756106020",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "hrmX7MV5hifoaBVjnrdpz698yABxrbBNAcWtWo9ondo",
    },
  },
  {
    name: "Invesco QQQ ETF",
    symbol: "QQQON",
    id: "invesco-qqq-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68654/large/qqqon_160x160.png?1756156339",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "HrYNm6jTQ71LoFphjVKBTdAE4uja7WsmLG8VxB8ondo",
    },
  },
  {
    name: "Reddit",
    symbol: "RDDTON",
    id: "reddit-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68585/large/rddton_160x160.png?1756129789",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "HXFrTf9v9NdjGUTnx4sojR3Cf92hoBsQFUxKTN7ondo",
    },
  },
  {
    name: "VanEck Rare Earth and Strategic Metals ETF",
    symbol: "REMXON",
    id: "vaneck-rare-earth-and-strategic-metals-etf-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71472/large/remxon_160x160.png?1767892092",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "tiitb2Z1HtpB2DpVr6V7tdCFS3jmTinLeuGj9EVondo",
    },
  },
  {
    name: "Rigetti Computing ",
    symbol: "RGTION",
    id: "rigetti-computing-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71462/large/rgtion_160x160.png?1767890590",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "dwEPNKQab3iwRmjGvZPXhAmws1W5NsQGwuXwi8oondo",
    },
  },
  {
    name: "Riot Platforms",
    symbol: "RIOTON",
    id: "riot-platforms-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68547/large/rioton_160x160.png?1756105446",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "i6f3DvZBuLpnGSqS8x6WPeStJ7jNe5KewD6afD5ondo",
    },
  },
  {
    name: "Rivian Automotive",
    symbol: "RIVNON",
    id: "rivian-automotive-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71463/large/rivnon_160x160.png?1767890637",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "AXRsYFt7TXNQ3DcY6BkvRgPV6VsYMURyDtaeudjondo",
    },
  },
  {
    name: "RTX ",
    symbol: "RTXON",
    id: "rtx-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71464/large/rtxon_160x160.png?1767890843",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "12BvLZtzjdssAycxPeBQUjukhmgQpULAvy6SroYdondo",
    },
  },
  {
    name: "SharpLink Gaming, Inc",
    symbol: "SBETON",
    id: "sharplink-gaming-inc-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68657/large/sbeton_160x160.png?1756156393",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "iLDu2jjp2i3Uqc2Vm7K7GLiUj3hR4Un49MtD7c4ondo",
    },
  },
  {
    name: "Starbucks",
    symbol: "SBUXON",
    id: "starbucks-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68564/large/sbuxon_160x160.png?1756106053",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "iPFqjcZQTNMNXA4kbShbMhfAVD8yr8Uq9UtXMV6ondo",
    },
  },
  {
    name: "Charles Schwab",
    symbol: "SCHWON",
    id: "charles-schwab-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71415/large/schwon_160x160.png?1767879904",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "cnc6M1zXLdrGR5LAQVcaJDfgezMiVWNtGQsVy1Kondo",
    },
  },
  {
    name: "iShares 0-3 Month Treasury Bond ETF",
    symbol: "SGOVON",
    id: "ishares-0-3-month-treasury-bond-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/71432/large/sgovon_160x160.png?1767882893",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "HjrN6ChZK2QRL6hMXayjGPLFvxhgjwKEy135VRjondo",
    },
  },
  {
    name: "Shopify",
    symbol: "SHOPON",
    id: "shopify-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68584/large/shopon_160x160.png?1756129783",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "ivdDracs2s7jCP698dJXKSEQdVrNj9hasJL1Uq1ondo",
    },
  },
  {
    name: "iShares Silver Trust",
    symbol: "SLVON",
    id: "ishares-silver-trust-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68651/large/slvon_160x160.png?1756156286",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "iy11ytbSGcUnrjE6Lfv78TFqxKyUESfku1FugS9ondo",
    },
  },
  {
    name: "Super Micro Computer",
    symbol: "SMCION",
    id: "super-micro-computer-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68559/large/smcion_160x160.png?1756105887",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "jLca79XzcewRuBZyaJxVxuKpUHcEix1X4CP1RP9ondo",
    },
  },
  {
    name: "Snap ",
    symbol: "SNAPON",
    id: "snap-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71465/large/snapon_160x160.png?1767890903",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "a2cXfonVgQ6cKB4Lm8YZsPry39VZSA562bwmRSiondo",
    },
  },
  {
    name: "Snowflake",
    symbol: "SNOWON",
    id: "snowflake-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68605/large/snowon_160x160.png?1756130024",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "JmFLCBwoNvcXy6B2VqABg6m784ubkXpaEx3p7S5ondo",
    },
  },
  {
    name: "SoFi Technologies",
    symbol: "SOFION",
    id: "sofi-technologies-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71579/large/sofion_160x160.webp?1768405245",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "mqL8yXQpeSvc7NgrAtLLPtRvUiWyLoG5RWLv16iondo",
    },
  },
  {
    name: "Southern",
    symbol: "SOON",
    id: "southern-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71580/large/soon_160x160.webp?1768405347",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "aKzjn2ZdWySSGPSSDTY2HUpcSCmemSahTXihrpyondo",
    },
  },
  {
    name: "SoundHound AI ",
    symbol: "SOUNON",
    id: "soundhound-ai-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71466/large/sounon_160x160.png?1767891383",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "vE2qArmjto6VfeMngyGAnzp2ipLYeXsxiARDnnXondo",
    },
  },
  {
    name: "S&P Global",
    symbol: "SPGION",
    id: "s-p-global-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68596/large/spgion_160x160.png?1756129901",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "JrTYw7A9jihX5TwpRStYviEbsYf2X2VJpZ13719ondo",
    },
  },
  {
    name: "Spotify",
    symbol: "SPOTON",
    id: "spotify-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68627/large/spoton_160x160.png?1756130300",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "jzCvs2Pk8tDcfsFRqnEMjurgaQW4iQfEkandUR8ondo",
    },
  },
  {
    name: "SPDR S&P 500 ETF",
    symbol: "SPYON",
    id: "spdr-s-p-500-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68655/large/spyon_160x160.png?1756156354",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "k18WJUULWheRkSpSquYGdNNmtuE2Vbw1hpuUi92ondo",
    },
  },
  {
    name: "ProShares UltraPro Short QQQ ",
    symbol: "SQQQON",
    id: "proshares-ultrapro-short-qqq-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71461/large/sqqqon_160x160.png?1767890553",
    kind: "stock",
    categories: ["Stocks", "Fund"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "D1tu7Fnm3cCpKyyPXrqm5GXShPqMj7a2SEjjq9fondo",
    },
  },
  {
    name: "Trip.com Group",
    symbol: "TCOMON",
    id: "trip-com-group-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71584/large/tcomon_160x160.webp?1768406201",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "9PMjLqd8zPdKkJUXarnit5t7tPL3cCscwHzy7ATondo",
    },
  },
  {
    name: "iShares TIPS Bond ETF",
    symbol: "TIPON",
    id: "ishares-tips-bond-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68542/large/tipon_160x160.png?1756105129",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "k6BPp2Xmf2TYgrZiUyWfUoZBKeqaDbvPoAVgSx2ondo",
    },
  },
  {
    name: "Talen Energy",
    symbol: "TLNON",
    id: "talen-energy-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71582/large/tlnon_160x160.webp?1768405587",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "RTb54gpqAx6RpLAHRGnqQ3ciQ845CHqhg21ZzEJondo",
    },
  },
  {
    name: "iShares 20+ Year Treasury Bond ETF",
    symbol: "TLTON",
    id: "ishares-20-year-treasury-bond-etf-ondo-tokenized-etf",
    logo: "https://coin-images.coingecko.com/coins/images/68647/large/tlton_160x160.png?1756156198",
    kind: "stock",
    categories: ["ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "KaSLSWByKy6b9FrCYXPEJoHmLpuFZtTCJk1F1Z9ondo",
    },
  },
  {
    name: "Toyota",
    symbol: "TMON",
    id: "toyota-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68583/large/tmon_160x160.png?1756129775",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "kbmF7ERJWMaaDswMprrH9gHSLya5D2RMBNgKqg3ondo",
    },
  },
  {
    name: "Thermo Fisher Scientific",
    symbol: "TMOON",
    id: "thermo-fisher-scientific-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71583/large/tmoon_160x160.webp?1768406109",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "T699bgtXQw4CJ59rQ4VzLsupVQUzoL5RmuhHnKrondo",
    },
  },
  {
    name: "T-Mobile US",
    symbol: "TMUSON",
    id: "t-mobile-us-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71581/large/tmuson_160x160.webp?1768405444",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "pDY4GPJfZcNETPG7myXeafQfgJqqVkn81bMYDyfondo",
    },
  },
  {
    name: "AT&T",
    symbol: "TON",
    id: "atnt-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/71570/large/ton_160x160.webp?1768403639",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "WKMZummev5UcXz5nNKQZvTD6QjNSM2X58uwmDReondo",
    },
  },
  {
    name: "ProShares UltraPro QQQ ",
    symbol: "TQQQON",
    id: "proshares-ultrapro-qqq-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71460/large/tqqqon_160x160.png?1767890499",
    kind: "stock",
    categories: ["Stocks", "Fund"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "14W1itEkV7k1W819mLSknFTaMmkCtPokbF2tRkPUondo",
    },
  },
  {
    name: "Tesla",
    symbol: "TSLAON",
    id: "tesla-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68628/large/tslaon_160x160.png?1756130306",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "KeGv7bsfR4MheC1CkmnAVceoApjrkvBhHYjWb67ondo",
    },
  },
  {
    name: "Taiwan Semiconductor Manufacturing",
    symbol: "TSMON",
    id: "taiwan-semiconductor-manufacturing-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68598/large/tsmon_160x160.png?1756129915",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Token2022", "Verified"],
    decimals: 9,
    mints: {
      mainnet: "keybg184d4vyXeQdFqs4o99YsMg7xBthxTJ6Ky3ondo",
    },
  },
  {
    name: "Texas Instruments (Ondo Tokenized)",
    symbol: "TXNON",
    id: "texas-instruments-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71470/large/txnon_160x160.png?1767891853",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "81xLFvCzFaUM3KDxSHC75pXu3RPCeSeCbmGBY8aondo",
    },
  },
  {
    name: "Uber",
    symbol: "UBERON",
    id: "uber-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68562/large/uberon_160x160.png?1756105997",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "KJNeFW3kk3ycPjXpC6cbuyckjeYHacc2ekhtAi5ondo",
    },
  },
  {
    name: "UnitedHealth",
    symbol: "UNHON",
    id: "unitedhealth-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68624/large/unhon_160x160.png?1756130276",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "kPBGL8vAwKN3UGmr9cjkM2dU79SC3nzTC9yu7F8ondo",
    },
  },
  {
    name: "WisdomTree Floating Rate Treasury Fund (Ondo Tokenized)",
    symbol: "USFRON",
    id: "wisdomtree-floating-rate-treasury-fund-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71478/large/usfron_160x160.png?1767892375",
    kind: "stock",
    categories: ["Stocks", "Fund"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "o6U1Sm6Vd7EofMyCrL28mrp2QLzgYGgjveHiEQ5ondo",
    },
  },
  {
    name: "United States Oil Fund (Ondo Tokenized)",
    symbol: "USOON",
    id: "united-states-oil-fund-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71471/large/usoon_160x160.png?1767892001",
    kind: "stock",
    categories: ["Stocks", "Fund"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "rpydAzWdCy85HEmoQkH5PVxYtDYQWjmLxgHHadxondo",
    },
  },
  {
    name: "Visa",
    symbol: "VON",
    id: "visa-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68626/large/von_160x160.png?1756130294",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "kxEW4oJL75K37VeXaZF1ynbHQATQwhECQKN1374ondo",
    },
  },
  {
    name: "Vertiv (Ondo Tokenized)",
    symbol: "VRTON",
    id: "vertiv-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71476/large/vrton_160x160.png?1767892296",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "MkN2TZSYTFBdMRLf9EVcfhstTwnazH8knd9hpepondo",
    },
  },
  {
    name: "Vistra (Ondo Tokenized)",
    symbol: "VSTON",
    id: "vistra-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71477/large/vston_160x160.png?1767892341",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "h6MW8GFpfzxFa1JNn6hZNnBF3t4fj9SHAXKy6LXondo",
    },
  },
  {
    name: "Vanguard Total Stock Market ETF (Ondo Tokenized)",
    symbol: "VTION",
    id: "vanguard-total-stock-market-etf-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71473/large/vtion_160x160.png?1767892132",
    kind: "stock",
    categories: ["Stocks", "ETF"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "jCCU4GwukjNxAXJowG2S4KCrr5g6YyUB61WHYvGondo",
    },
  },
  {
    name: "Vanguard Value ETF (Ondo Tokenized)",
    symbol: "VTVON",
    id: "vanguard-value-etf-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71474/large/vtvon_160x160.png?1767892219",
    kind: "stock",
    categories: ["ETF", "Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "KuiYLPVq65qixD9TgvxBC576C4gG6vVTCdbh2zFondo",
    },
  },
  {
    name: "Verizon (Ondo Tokenized)",
    symbol: "VZON",
    id: "verizon-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71475/large/vzon_160x160.png?1767892257",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "igu1coP6n3GPaWmbd8J9Z7UAyLpV254uQFFNfydondo",
    },
  },
  {
    name: "Wells Fargo",
    symbol: "WFCON",
    id: "wells-fargo-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68590/large/wfcon_160x160.png?1756129819",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "L6ZE5qCpVVSqLePz64CrwkgyWoPF9M7tB8BeFH4ondo",
    },
  },
  {
    name: "Walmart",
    symbol: "WMTON",
    id: "walmart-ondo-tokenized-stock",
    logo: "https://coin-images.coingecko.com/coins/images/68582/large/wmton_160x160.png?1756129770",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "LZddqAqKqJW9oMZSjTxCUmbmzBRQtv9gMkD9hZ3ondo",
    },
  },
  {
    name: "Terawulf (Ondo Tokenized)",
    symbol: "WULFON",
    id: "terawulf-ondo-tokenized",
    logo: "https://coin-images.coingecko.com/coins/images/71469/large/wulfon_160x160.png?1767891803",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "exYfSJt6Fgfhfnp3bAD4roYy97hLF9npjYaLyEXondo",
    },
  },
  {
    name: "Exxon Mobil",
    symbol: "XOMON",
    id: "exxon-mobil-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71421/large/xomon_160x160.png?1767881375",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "qCYD74QnXzd9pzv6pGHQKJVwoibL6sNcPQDnpDiondo",
    },
  },
  {
    name: "Block",
    symbol: "XYZON",
    id: "block-ondo-tokenized-stocks",
    logo: "https://coin-images.coingecko.com/coins/images/71412/large/xyzon_160x160.png?1767879216",
    kind: "stock",
    categories: ["Stocks"],
    tags: ["Verified", "Token2022"],
    decimals: 9,
    mints: {
      mainnet: "BWxe2FVciUbwrCUZQPUKiREBh5LmVa5AiUqNLAkondo",
    },
  },

  // ---------------- PreMarket (tokenized)
  {
    name: "SpaceX",
    symbol: "SPACEX",
    id: "spacex-prestocks-2",
    logo: "/logos/spacex.png",
    kind: "stock",
    categories: ["PreMarket", "Stocks"],
    tags: ["Index"],
    decimals: 8,
    mints: { mainnet: "PreANxuXjsy2pvisWWMNB6YaJNzr7681wJJr2rHsfTh" },
  },
  {
    name: "Anthropic",
    symbol: "ANTHROPIC",
    id: "anthropic-prestocks-2",
    logo: "/logos/anthropic.png",
    kind: "stock",
    categories: ["PreMarket", "Stocks"],
    tags: ["Index"],
    decimals: 8,
    mints: { mainnet: "Pren1FvFX6J3E4kXhJuCiAD5aDmGEb7qJRncwA8Lkhw" },
  },
  {
    name: "xAI",
    symbol: "XAI",
    id: "xai-prestocks-2",
    logo: "/logos/xai.png",
    kind: "stock",
    categories: ["PreMarket", "Stocks"],
    tags: ["Index"],
    decimals: 8,
    mints: { mainnet: "PreC1KtJ1sBPPqaeeqL6Qb15GTLCYVvyYEwxhdfTwfx" },
  },
  {
    name: "OpenAI",
    symbol: "OPENAI",
    id: "openai-prestocks-2",
    logo: "/logos/openai.png",
    kind: "stock",
    categories: ["PreMarket", "Stocks"],
    tags: ["Index"],
    decimals: 8,
    mints: { mainnet: "PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF" },
  },
  //--------------------- Commodity
  {
    name: "GOLD(1 T OZ)",
    symbol: "GLD",
    id: "",
    logo: "/logos/gldoz.png",
    kind: "stock",
    categories: ["Commodity"],
    tags: ["Commodity"],
    decimals: 8,
    mints: { mainnet: "GoLDppdjB1vDTPSGxyMJFqdnj134yH6Prg9eqsGDiw6A" },
  },
  {
    name: "SILVER",
    symbol: "SLV",
    id: "",
    logo: "/logos/slv.png",
    kind: "stock",
    categories: ["Commodity"],
    tags: ["Commodity"],
    decimals: 8,
    mints: { mainnet: "7C56WnJ94iEP7YeH2iKiYpvsS5zkcpP9rJBBEBoUGdzj" },
  },
  {
    name: "COPPER",
    symbol: "CPER",
    id: "",
    logo: "/logos/cper.png",
    kind: "stock",
    categories: ["Commodity"],
    tags: ["Commodity"],
    decimals: 8,
    mints: { mainnet: "C3VLBJB2FhEb47s1WEgroyn3BnSYXaezqtBuu5WNmUGw" },
  },
  {
    name: "PLATINUM",
    symbol: "PPLT",
    id: "",
    logo: "/logos/pt.png",
    kind: "stock",
    categories: ["Commodity"],
    tags: ["Commodity"],
    decimals: 8,
    mints: { mainnet: "EtTQ2QRyf33bd6B2uk7nm1nkinrdGKza66EGdjEY4s7o" },
  },
];

// Backwards compatible: existing code can keep importing TOKENS
export const TOKENS: TokenMeta[] = [...STOCK_TOKENS, ...CRYPTO_TOKENS];

/* ------------------------------- Finders -------------------------------- */

export function getMintFor(
  token: Pick<TokenMeta, "mints">,
  cluster: Cluster = getCluster(),
): string | null {
  return token.mints[cluster] ?? null;
}

export function tokensForCluster(cluster: Cluster = getCluster()): TokenMeta[] {
  return TOKENS.filter((t) => !!t.mints[cluster]);
}

export function findTokenBySymbol(symbol: string): TokenMeta | undefined {
  const s = symbol.trim().toUpperCase();
  return TOKENS.find((t) => t.symbol.toUpperCase() === s);
}

export function findTokenByMint(
  mint: string,
  cluster: Cluster = getCluster(),
): TokenMeta | undefined {
  const m = mint.trim();
  return TOKENS.find((t) => t.mints[cluster] === m);
}

export function requireMintBySymbol(
  symbol: string,
  cluster: Cluster = getCluster(),
): string {
  const t = findTokenBySymbol(symbol);
  if (!t) throw new Error(`Unknown token symbol: ${symbol}`);
  const mint = t.mints[cluster];
  if (!mint)
    throw new Error(
      `Token ${symbol} is not enabled on ${cluster}. Add its mint in TOKENS[].mints.${cluster}.`,
    );
  return mint;
}

/* --------------------------- Filtering helpers -------------------------- */

export function tokensByCategory(
  category: TokenCategory,
  cluster: Cluster = getCluster(),
): TokenMeta[] {
  return TOKENS.filter(
    (t) => !!t.mints[cluster] && t.categories.includes(category),
  );
}

export function tokensByCategories(
  categories: TokenCategory[],
  mode: "any" | "all" = "any",
  cluster: Cluster = getCluster(),
): TokenMeta[] {
  const wanted = new Set(categories);
  return TOKENS.filter((t) => {
    if (!t.mints[cluster]) return false;
    const have = new Set(t.categories);
    if (mode === "all") {
      for (const c of wanted) if (!have.has(c)) return false;
      return true;
    }
    // any
    for (const c of wanted) if (have.has(c)) return true;
    return false;
  });
}

export function tokensByTag(
  tag: string,
  cluster: Cluster = getCluster(),
): TokenMeta[] {
  const q = tag.trim().toLowerCase();
  return TOKENS.filter(
    (t) =>
      !!t.mints[cluster] && (t.tags ?? []).some((x) => x.toLowerCase() === q),
  );
}

/* ------------------------- Optional convenience ------------------------- */
// If you want direct list getters without categories logic:
export function stockTokensForCluster(
  cluster: Cluster = getCluster(),
): TokenMeta[] {
  return STOCK_TOKENS.filter((t) => !!t.mints[cluster]);
}

export function cryptoTokensForCluster(
  cluster: Cluster = getCluster(),
): TokenMeta[] {
  return CRYPTO_TOKENS.filter((t) => !!t.mints[cluster]);
}

